# Generated by Django 5.0.7 on 2024-08-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_diary_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='diary_yn',
        ),
    ]
