# Generated by Django 5.0.7 on 2024-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_diary_diary_yn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='emoj',
            new_name='emotion',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='emotion1',
            new_name='tag1',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='emotion2',
            new_name='tag2',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='emotion3',
            new_name='tag3',
        ),
        migrations.AddField(
            model_name='diary',
            name='feel',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
