# Generated by Django 4.2.14 on 2024-08-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfTest', '0007_self_test_result_result_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=10)),
            ],
        ),
    ]
