# Generated by Django 4.2.14 on 2024-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs_theme', models.CharField(max_length=2)),
                ('qs_content', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quest_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('qs_theme', models.CharField(max_length=2)),
                ('qs_content', models.CharField(max_length=30)),
                ('qs_date', models.DateField(auto_now_add=True)),
                ('qs_perform_yn', models.BooleanField(default=False)),
                ('qs_perform_content', models.TextField(blank=True)),
                ('qs_perform_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
