# Generated by Django 4.2.14 on 2024-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_alter_quest_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest_history',
            name='qs_perform_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
